// Zod runtime schema for StrategyDefinition.
import { z } from 'zod';
const signalRefSchema = z.object({ signalId: z.string().min(1) });
const operatorSchema = z.enum(['gt','gte','lt','lte','eq','neq','crosses_above','crosses_below','is_true','is_false']);
const conditionSchema = z.object({ type: z.literal('condition'), left: signalRefSchema, operator: operatorSchema, right: z.union([signalRefSchema, z.number()]).optional() });
const conditionGroupSchema = z.lazy(() => z.object({ type: z.literal('group'), logic: z.enum(['AND','OR']), children: z.array(z.union([conditionSchema, conditionGroupSchema])).max(50) }));
const signalKindSchema = z.enum(['open','high','low','close','volume','sma','ema','rsi','atr','macd_line','macd_signal','macd_hist','bb_upper','bb_middle','bb_lower','vwap','rel_volume','volume_spike','fvg_bullish','fvg_bearish','order_block_bullish','order_block_bearish','bos_bullish','bos_bearish','liquidity_sweep_high','liquidity_sweep_low','equal_highs','equal_lows','premium_zone','discount_zone','kill_zone','orb_bullish','orb_bearish']);
const signalSpecSchema = z.object({ id: z.string().min(1).max(64).regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/), kind: signalKindSchema, params: z.record(z.union([z.number(), z.string()])).optional() });
export const strategyDefinitionSchema = z.object({ name: z.string().min(1).max(120), symbol: z.string().min(1).max(15), direction: z.enum(['long','short','both']), signals: z.array(signalSpecSchema).max(50), entry: conditionGroupSchema, exit: conditionGroupSchema, advancedExpression: z.object({ entry: z.string().max(1000).optional(), exit: z.string().max(1000).optional() }).optional(), risk: z.object({ positionSizePct: z.number().min(0.01).max(100), stopLossPct: z.number().min(0.01).max(100).optional(), takeProfitPct: z.number().min(0.01).max(1000).optional(), maxBarsInTrade: z.number().int().min(1).max(100000).optional() }), initialCapital: z.number().min(1).max(1_000_000_000) });
export const backtestRequestSchema = z.object({ strategy: strategyDefinitionSchema, startDate: z.string(), endDate: z.string(), interval: z.enum(['1d','1h','30m','15m','5m']).default('1d') });
